### ISSUE TITLE
Compose version Alpha-10?

### ISSUE THREAD

**Issue by jobinlawrance** [sigmadeltasoftware/CalPose#2]
Any estimate on when the library will be updated to Jetpack Compose Alpha-10?

**Comment by sigmadeltasoftware** [comment]
Hey Jobin, I just pushed the update (V1.0.2) to Jitpack so I expect it to be deployed pretty soon. 👍

**Comment by jobinlawrance** [comment]
Thank you so much, appreciate the effort 😊
