### ISSUE TITLE
Crash with beta04

### ISSUE THREAD

**Issue by teal77** [sigmadeltasoftware/CalPose#4]
`java.lang.NoSuchFieldError: No static field Companion of type Landroidx/compose/foundation/layout/ColumnScope$Companion; in class Landroidx/compose/foundation/layout/ColumnScope;`

There was a mention of ColumnScope, RowScope in latest changelogs. So it's possibly related.

>[Public instances of RowScope, ColumnScope, BoxScope, BoxWithConstraintsScope were removed. (I4e83e, b/181869067)](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.0.0-beta04)

**Comment by sigmadeltasoftware** [comment]
Hi @teal77, this should be fixed in our latest versions. Please refer to `v1.0.5`.
