### ISSUE TITLE
CalPose v1.0.5 doesnt contain last changes.

### ISSUE THREAD

**Issue by varpihovsky** [sigmadeltasoftware/CalPose#8]
Hello, last release is based on bbb881a commit, when last one is 0fd2021.

**Comment by sigmadeltasoftware** [comment]
Hey @varpihovsky, I saw indeed. Currently updating it as we speak to have the right reference: https://jitpack.io/com/github/sigmadeltasoftware/CalPose/1.0.5/build.log
